# Generated by Django 2.2.12 on 2020-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(max_length=120, verbose_name='Quiz Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
